In [11]:
import pandas as pd
# from google.colab import files
# files.upload()
df = pd.read_csv("titanic.csv")
df.sample(5)

    Cabin     Ticket number  Survived
270   NaN     113798      5         0
422   NaN     315082      2         0
746   NaN  C.A. 2673      1         0
650   NaN     349221      5         0
127   NaN    C 17369      4         1

In [12]:
df['number'].apply(lambda x: 0 if x == 'A' else x )
# A(alone) is replaced by 0

0      5
1      3
2      6
3      3
4      0
      ..
886    3
887    3
888    1
889    2
890    3
Name: number, Length: 891, dtype: object

In [14]:
import numpy as np
# extract numerical part
df['number_numerical'] = pd.to_numeric(df["number"],errors='coerce',downcast='integer')
# extract categorical part
df['number_categorical'] = np.where(df['number_numerical'].isnull(),df['number'],np.nan)
df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical
0,NaN,A/5 21171,5,0,5.0,NaN
1,C85,PC 17599,3,1,3.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN
3,C123,113803,3,1,3.0,NaN
4,NaN,373450,A,0,NaN,A

In [19]:
df['Cabin_num'] = df['Cabin'].str.extract('(\d+)')
df['Cabin_cate'] = df['Cabin'].str[0]
df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,Cabin_num,Cabin_cate
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN

In [20]:
# extract the last bit of ticket as number
df['ticket_num'] = df['Ticket'].apply(lambda s: s.split()[-1])
df['ticket_num'] = pd.to_numeric(df['ticket_num'],
                                   errors='coerce',
                                   downcast='integer')

# extract the first part of ticket as category
df['ticket_cat'] = df['Ticket'].apply(lambda s: s.split()[0])
df['ticket_cat'] = np.where(df['ticket_cat'].str.isdigit(), np.nan,
                              df['ticket_cat'])

df.head(20)

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,Cabin_num,Cabin_cate,ticket_num,ticket_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,21171.0,A/5
1,C85,PC 17599,3,1,3.0,NaN,85,C,17599.0,PC
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,3101282.0,STON/O2.
3,C123,113803,3,1,3.0,NaN,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,A,NaN,NaN,373450.0,NaN
5,NaN,330877,2,0,2.0,NaN,NaN,NaN,330877.0,NaN
6,E46,17463,2,0,2.0,NaN,46,E,17463.0,NaN
7,NaN,349909,5,0,5.0,NaN,NaN,NaN,349909.0,NaN
8,NaN,347742,1,1,1.0,NaN,NaN,NaN,347742.0,NaN
9,NaN,237736,A,1,NaN,A,NaN,NaN,237736.0,NaN
10,G6,PP 9549,1,1,1.0,NaN,6,G,9549.0,PP
11,C103,113783,1,1,1.0,NaN,103,C,113783.0,NaN
12,NaN,A/5. 2151,3,0,3.0,NaN,NaN,NaN,2151.0,A/5.
13,NaN,347082,3,0,3.0,NaN,NaN,NaN,347082.0,NaN
14,NaN,350406,5,0,5.0,NaN,NaN,NaN,350406.0,NaN
15,NaN,248706,3,1,3.0,NaN,NaN,NaN,248706.0,NaN
16,NaN,382652,3,0,3.0,NaN,NaN,NaN,382652.0,NaN
17,NaN,244373,2,1,2.0,NaN,NaN,NaN,244373.0,NaN
18,NaN,345763,5,0,5.0,NaN,NaN,NaN,345763.0,NaN
19,NaN,2649,4,1,4.0,NaN,NaN,NaN,2649.0,NaN